import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Swal from 'sweetalert2';
import { useAuth } from '../context/AuthContext';
import { obtenerCarrito, resumenCarrito, crearPedido } from '../utils/shopCore';

const input = {width:'100%',background:'var(--pg-input)',border:'1px solid var(--pg-border2)',borderRadius:'10px',padding:'10px 13px',color:'var(--pg-text)',outline:'none',fontFamily:"'Inter',sans-serif",boxSizing:'border-box'};
const label = {display:'block',fontSize:'11px',fontWeight:'800',color:'var(--pg-muted2)',marginBottom:'7px',textTransform:'uppercase',letterSpacing:'.05em'};

export default function PubCheckout(){
  const navigate = useNavigate();
  const { isAuth, usuario } = useAuth();
  const items = useMemo(() => obtenerCarrito(), []);
  const r = useMemo(() => resumenCarrito(items), [items]);
  const [step,setStep]=useState(1);
  const [cliente,setCliente]=useState({ nombre: usuario?.nombre || '', documento:'', email: usuario?.email || '', telefono:'', tipoDoc:'DNI' });
  const [entrega,setEntrega]=useState({ tipo:'DELIVERY', direccion:'', referencia:'', distrito:'', ciudad:'Pucallpa' });
  const [pago,setPago]=useState({ metodo:'Yape', operacion:'', comprobante:'Boleta' });

  if(!items.length){
    return <div style={{padding:'40px',background:'var(--pg-bg)',color:'var(--pg-text)',minHeight:'100%'}}><h1>No hay productos en tu carrito</h1><button className="pg-anim-btn" onClick={()=>navigate('/s/ofertas')} style={{background:'#7c3aed',color:'white',border:'none',borderRadius:'10px',padding:'12px 18px',fontWeight:'800'}}>Ver ofertas</button></div>;
  }

  const validar = () => {
    if(step===1 && (!cliente.nombre || !cliente.telefono || !cliente.documento)) return 'Completa nombre, documento y teléfono.';
    if(step===2 && entrega.tipo==='DELIVERY' && !entrega.direccion) return 'Ingresa tu dirección para delivery.';
    return '';
  };

  const siguiente=()=>{ const e=validar(); if(e) return Swal.fire({icon:'warning',title:e,confirmButtonColor:'#7c3aed',background:'var(--pg-surface)',color:'var(--pg-text)',width:'380px'}); setStep(s=>Math.min(3,s+1)); };
  const finalizar=()=>{
    const e=validar(); if(e) return Swal.fire({icon:'warning',title:e,confirmButtonColor:'#7c3aed',background:'var(--pg-surface)',color:'var(--pg-text)',width:'380px'});
    const pedido = crearPedido({ cliente, entrega, pago });
    Swal.fire({icon:'success',title:'Compra finalizada',text:'Se generó tu Boleta de Venta Electrónica.',timer:1400,showConfirmButton:false,background:'var(--pg-surface)',color:'var(--pg-text)'});
    setTimeout(()=>navigate(`/s/boleta/${pedido.id}`), 900);
  };

  const stepStyle=(n)=>({height:'32px',borderRadius:'999px',padding:'0 16px',display:'flex',alignItems:'center',gap:'8px',fontWeight:'900',background:step>=n?'linear-gradient(135deg,#7c3aed,#9333ea)':'var(--pg-input)',border:'1px solid var(--pg-border2)',color:step>=n?'white':'var(--pg-muted2)'});

  return <div className="pub-checkout-page" style={{padding:'22px 24px',paddingBottom:'120px',fontFamily:"'Inter',sans-serif",background:'var(--pg-bg)',color:'var(--pg-text)',minHeight:'100%'}}>
    <style>{`@media(max-width:820px){.pub-checkout-page{padding:14px 10px 105px!important}.pub-checkout-head{flex-direction:column!important;align-items:flex-start!important}.pub-checkout-head button{width:100%!important}.pub-checkout-steps{overflow-x:auto!important}.pub-checkout-grid{grid-template-columns:1fr!important}.pub-checkout-form-grid,.pub-checkout-two-grid,.pub-checkout-pay-grid{grid-template-columns:1fr!important}.pub-checkout-form-grid>div{grid-column:auto!important}.pub-checkout-row-actions{gap:10px!important}.pub-checkout-row-actions button{flex:1!important}}`}</style><div className="pub-checkout-head" style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'18px'}}><div><h1 style={{margin:'0 0 4px',fontSize:'22px',fontWeight:'900'}}>Proceso de compra</h1><p style={{margin:0,color:'var(--pg-muted)'}}>{isAuth?'Compra con tu cuenta PartGo':'Puedes iniciar sesión, registrarte o comprar como invitado.'}</p></div><button className="pg-anim-btn" onClick={()=>navigate('/s/carrito')} style={{background:'transparent',border:'1px solid var(--pg-border2)',color:'var(--pg-muted2)',borderRadius:'9px',padding:'9px 14px',cursor:'pointer'}}>← Volver al carrito</button></div>

    <div className="pub-checkout-steps" style={{display:'flex',gap:'10px',marginBottom:'18px'}}><div style={stepStyle(1)}>1 Datos</div><div style={stepStyle(2)}>2 Entrega</div><div style={stepStyle(3)}>3 Pago</div></div>

    <div className="pub-checkout-grid" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 310px',gap:'18px'}}>
      <section style={{background:'var(--pg-card)',border:'1px solid var(--pg-border)',borderRadius:'16px',padding:'20px',boxShadow:'var(--pg-shadow)'}}>
        {step===1&&<div><h2 style={{margin:'0 0 14px',fontSize:'24px'}}>Datos del cliente</h2><div className="pub-checkout-form-grid" style={{display:'grid',gridTemplateColumns:'160px 1fr 1fr',gap:'14px'}}><div><label style={label}>Documento</label><select value={cliente.tipoDoc} onChange={e=>setCliente({...cliente,tipoDoc:e.target.value})} style={input}><option>DNI</option><option>RUC</option></select></div><div><label style={label}>Nro. documento</label><input value={cliente.documento} onChange={e=>setCliente({...cliente,documento:e.target.value})} style={input} placeholder="12345678"/></div><div><label style={label}>Nombre completo</label><input value={cliente.nombre} onChange={e=>setCliente({...cliente,nombre:e.target.value})} style={input} placeholder="Juan Pérez"/></div><div><label style={label}>Teléfono</label><input value={cliente.telefono} onChange={e=>setCliente({...cliente,telefono:e.target.value})} style={input} placeholder="987654321"/></div><div style={{gridColumn:'span 2'}}><label style={label}>Correo</label><input value={cliente.email} onChange={e=>setCliente({...cliente,email:e.target.value})} style={input} placeholder="cliente@gmail.com"/></div></div></div>}
        {step===2&&<div><h2 style={{margin:'0 0 14px',fontSize:'24px'}}>Entrega</h2><div style={{display:'flex',gap:'10px',marginBottom:'16px'}}>{['DELIVERY','RECOJO'].map(x=><button key={x} className="pg-anim-btn" onClick={()=>setEntrega({...entrega,tipo:x})} style={{flex:1,background:entrega.tipo===x?'linear-gradient(135deg,#7c3aed,#9333ea)':'var(--pg-input)',color:entrega.tipo===x?'white':'var(--pg-text)',border:'1px solid var(--pg-border2)',borderRadius:'10px',padding:'12px',fontWeight:'900',cursor:'pointer'}}>{x==='DELIVERY'?'🚚 Delivery':'🏪 Recojo en tienda'}</button>)}</div>{entrega.tipo==='DELIVERY'?<div style={{display:'grid',gap:'14px'}}><div><label style={label}>Dirección</label><input value={entrega.direccion} onChange={e=>setEntrega({...entrega,direccion:e.target.value})} style={input} placeholder="Av. / Jr. / Calle"/></div><div className="pub-checkout-two-grid" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'14px'}}><div><label style={label}>Distrito</label><input value={entrega.distrito} onChange={e=>setEntrega({...entrega,distrito:e.target.value})} style={input}/></div><div><label style={label}>Ciudad</label><input value={entrega.ciudad} onChange={e=>setEntrega({...entrega,ciudad:e.target.value})} style={input}/></div></div><div><label style={label}>Referencia</label><input value={entrega.referencia} onChange={e=>setEntrega({...entrega,referencia:e.target.value})} style={input} placeholder="Casa color..., frente a..."/></div></div>:<div style={{background:'var(--pg-input)',border:'1px solid var(--pg-border2)',borderRadius:'12px',padding:'18px'}}><b>Recojo en tienda PartGo</b><p style={{color:'var(--pg-muted)',margin:'6px 0 0'}}>Av. Los Próceres 123, Lima - Perú. Atención: Lunes a sábado.</p></div>}</div>}
        {step===3&&<div><h2 style={{margin:'0 0 14px',fontSize:'24px'}}>Pago y comprobante</h2><div className="pub-checkout-pay-grid" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'10px',marginBottom:'16px'}}>{['Yape','Plin','Tarjeta','Efectivo'].map(x=><button key={x} className="pg-anim-btn" onClick={()=>setPago({...pago,metodo:x})} style={{background:pago.metodo===x?'linear-gradient(135deg,#7c3aed,#9333ea)':'var(--pg-input)',color:pago.metodo===x?'white':'var(--pg-text)',border:'1px solid var(--pg-border2)',borderRadius:'10px',padding:'12px',fontWeight:'900',cursor:'pointer'}}>{x}</button>)}</div><div className="pub-checkout-two-grid" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'14px'}}><div><label style={label}>Nro. operación / referencia</label><input value={pago.operacion} onChange={e=>setPago({...pago,operacion:e.target.value})} style={input} placeholder="Opcional"/></div><div><label style={label}>Comprobante</label><select value={pago.comprobante} onChange={e=>setPago({...pago,comprobante:e.target.value})} style={input}><option>Boleta</option><option>Factura</option></select></div></div><p style={{color:'var(--pg-muted)',fontSize:'12px',marginTop:'14px'}}>Al finalizar se generará una representación de Boleta de Venta Electrónica para Perú.</p></div>}
        <div className="pub-checkout-row-actions" style={{display:'flex',justifyContent:'space-between',marginTop:'22px'}}><button className="pg-anim-btn" onClick={()=>setStep(s=>Math.max(1,s-1))} disabled={step===1} style={{background:'transparent',border:'1px solid var(--pg-border2)',color:'var(--pg-muted2)',borderRadius:'10px',padding:'11px 18px',cursor:step===1?'not-allowed':'pointer'}}>Atrás</button>{step<3?<button className="pg-anim-btn" onClick={siguiente} style={{background:'linear-gradient(135deg,#7c3aed,#9333ea)',border:'none',borderRadius:'10px',padding:'11px 22px',color:'white',fontWeight:'900',cursor:'pointer'}}>Continuar</button>:<button className="pg-anim-btn" onClick={finalizar} style={{background:'linear-gradient(135deg,#16a34a,#22c55e)',border:'none',borderRadius:'10px',padding:'11px 22px',color:'white',fontWeight:'900',cursor:'pointer'}}>Finalizar compra y generar boleta</button>}</div>
      </section>
      <aside style={{background:'var(--pg-card)',border:'1px solid var(--pg-border)',borderRadius:'16px',padding:'18px',height:'fit-content',boxShadow:'var(--pg-shadow)'}}><h2 style={{margin:'0 0 14px'}}>Resumen</h2>{items.map(p=><div key={p.id} style={{display:'flex',gap:'10px',marginBottom:'10px'}}><img src={p.img} style={{width:'52px',height:'52px',objectFit:'contain',background:'#f5f5fc',borderRadius:'8px'}}/><div style={{flex:1}}><b style={{fontSize:'12px'}}>{p.nombre}</b><p style={{margin:'3px 0 0',color:'var(--pg-muted)',fontSize:'11px'}}>x{p.cantidad} · S/ {Number(p.precio).toFixed(2)}</p></div></div>)}<div style={{height:'1px',background:'var(--pg-border)',margin:'12px 0'}}/><p style={{display:'flex',justifyContent:'space-between'}}><span>Subtotal</span><b>S/ {r.subtotal.toFixed(2)}</b></p><p style={{display:'flex',justifyContent:'space-between'}}><span>Descuento</span><b style={{color:'#10b981'}}>- S/ {r.descuento.toFixed(2)}</b></p><p style={{display:'flex',justifyContent:'space-between'}}><span>Envío</span><b>S/ {r.envio.toFixed(2)}</b></p><h2 style={{display:'flex',justifyContent:'space-between'}}><span>Total</span><span style={{color:'#a78bfa'}}>S/ {r.total.toFixed(2)}</span></h2></aside>
    </div>
  </div>;
}
